import fs from 'fs';
import path from 'path';

// Path to the compiled library folder
const DIST = path.resolve('./dist');

// Helper function to create a Node-compatible export path
const makeExportPath = (file) =>
  `./${path.relative(process.cwd(), file).replace(/\\/g, '/')}`;

// Folders generated by bundlers or internal tooling that should not be exported
// Ignore configured folders (e.g. bundler virtual folders like _virtual created by Vite/Rolldown)
const IGNORED_DIRS = ['_virtual'];

// The package is ESM-only, so there is no `.cjs` to hand to the `require` condition. Without a trailing `default`
// the subpath resolves to nothing outside the `import` condition and Node answers ERR_PACKAGE_PATH_NOT_EXPORTED —
// even on versions that can require() ESM. Pointing `default` at the ESM entry lets require(esm) and any tool with
// an unusual condition set resolve it. Must stay LAST: conditions are matched in declaration order.
// Conditions are matched in declaration order, so `types` must lead (TypeScript takes the first condition it
// understands) and `default` must trail (it matches everything).
const CONDITION_ORDER = ['types', 'import', 'require'];

const withDefault = (exportEntry) => {
  const ordered = {};
  for (const condition of CONDITION_ORDER) {
    if (exportEntry[condition]) {
      ordered[condition] = exportEntry[condition];
    }
  }

  if (exportEntry.import) {
    ordered.default = exportEntry.import;
  }

  return ordered;
};

function hasMeaningfulExports(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');

  // remove comments, then drop the bare `export {}` TypeScript appends to mark a file as a module — it says
  // nothing about whether the file exports anything, and treating it as a disqualifier used to strip the `types`
  // condition off every declaration file that ended with one.
  const cleaned = content
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '')
    .replace(/export\s*\{\s*\}\s*;?/g, '')
    .trim();

  // should contain something exportable
  return cleaned.includes('export');
}

/**
 * Recursively scans the dist folder and generates exports
 *
 * @param {string} dir - Current directory to scan
 * @param {string} prefix - Prefix for the export key
 * @returns {object} Exports object
 */
function generateExports(dir, prefix = '.') {
  const exportsObj = {};
  if (!fs.existsSync(dir)) {
    return exportsObj;
  }

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory() && IGNORED_DIRS.includes(entry.name)) {
      continue;
    }

    // Key in exports, always starting with './'
    const key =
      prefix === '.'
        ? `./${entry.name.replace(/\.mjs$/, '')}`
        : `${prefix}/${entry.name.replace(/\.mjs$/, '')}`;

    if (entry.isDirectory()) {
      // For folders, check if index.mjs / index.cjs / index.d.ts exist
      const indexFiles = {
        types: path.join(entryPath, 'index.d.ts'),
        import: path.join(entryPath, 'index.mjs'),
        require: path.join(entryPath, 'index.cjs')
      };

      const exportEntry = {};
      // Only add paths that exist
      for (const [type, filePath] of Object.entries(indexFiles)) {
        if (fs.existsSync(filePath) && hasMeaningfulExports(filePath)) {
          exportEntry[type] = makeExportPath(filePath);
        }
      }

      if (
        Object.keys(exportEntry).length &&
        (exportEntry.import || exportEntry.require) &&
        exportEntry.types
      ) {
        exportsObj[key] = withDefault(exportEntry);
      }

      // Recursively scan subfolders
      Object.assign(exportsObj, generateExports(entryPath, key));
    } else if (entry.isFile() && entry.name.endsWith('.mjs')) {
      // For single .mjs files
      const files = {
        types: entryPath.replace(/\.mjs$/, '.d.ts'),
        import: entryPath,
        require: entryPath.replace(/\.mjs$/, '.cjs')
      };
      const exportEntry = {};
      for (const [type, filePath] of Object.entries(files)) {
        if (fs.existsSync(filePath) && hasMeaningfulExports(filePath)) {
          exportEntry[type] = makeExportPath(filePath);
        }
      }
      // Fallback: dts may be in a subdirectory with index.d.ts (e.g. react.mjs -> react/index.d.ts)
      if (!exportEntry.types) {
        const dirTypes = path.join(entryPath.replace(/\.mjs$/, ''), 'index.d.ts');
        if (fs.existsSync(dirTypes) && hasMeaningfulExports(dirTypes)) {
          exportEntry.types = makeExportPath(dirTypes);
        }
      }
      if (Object.keys(exportEntry).length) {
        exportsObj[key] = withDefault(exportEntry);
      }
    }
  }

  return exportsObj;
}

// Handle the main entry of the library (dist/index.*)
const mainIndex = {
  types: path.join(DIST, 'index.d.ts'),
  import: path.join(DIST, 'index.mjs'),
  require: path.join(DIST, 'index.cjs')
};
const mainExports = {};
for (const [type, file] of Object.entries(mainIndex)) {
  if (fs.existsSync(file)) {
    mainExports['.'] = { ...mainExports['.'], [type]: makeExportPath(file) };
  }
}
if (mainExports['.']) {
  mainExports['.'] = withDefault(mainExports['.']);
}

// Read current package.json
const pkgPath = path.resolve('./package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

// Merge main entry and recursive exports
pkg.exports = { ...mainExports, ...generateExports(DIST) };

// Write updated package.json
fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

console.log(
  '✅ package.json updated with automatic exports for the entire library'
);
